<a href="https://colab.research.google.com/github/joyhwp/personal_projects/blob/main/07_LLM_Engineering_Sessions/RAG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

💡 **NOTE**: 이 노트북의 코드를 실행하려면 GPU를 사용하는 것이 좋습니다. 구글 코랩에서는 **런타임 > 런타임 유형 변경 > 하드웨어 가속기 > T4 GPU**를 선택하세요.

---

사용 패키지 버전

* transformers 4.57.3
* cohere 5.20.1
* faiss-cpu 1.13.2
* rank-bm25 0.2.2
* langchain-community 0.4.1
* langchain-huggingface 1.2.0

In [ ]:
# 깃허브에서 위젯 상태 오류를 피하기 위해 진행 표시줄을 나타내지 않도록 설정합니다.
from transformers.utils import logging

logging.disable_progress_bar()

In [ ]:
%%capture
!pip install cohere faiss-cpu rank_bm25 langchain-community langchain_huggingface

# 사용하는 파이썬과 CUDA 버전에 맞는 llama-cpp-python 패키지를 설치하세요.
# 현재 코랩의 파이썬 버전은 3.12이며 CUDA 버전은 12.4(5)입니다.
!pip install https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.16-cu124/llama_cpp_python-0.3.16-cp312-cp312-linux_x86_64.whl

## 밀집 검색 예제

### 1. 텍스트 문서 분할하기

https://dashboard.cohere.com/api-keys

In [ ]:
import cohere

# 코히어의 API 키를 입력하세요.
api_key = 'WlBAG8dLX74yrFGVOS3pmEUn5oI5iBd7nHJq8oYG'

# 코히어 클라이언트를 만듭니다.
co = cohere.Client(api_key)

In [ ]:
text = """
Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan.
It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine.
Set in a dystopian future where humanity is struggling to survive, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for mankind.

Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007.
Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar.
Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm.
Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles.
Interstellar uses extensive practical and miniature effects and the company Double Negative created additional digital effects.

Interstellar premiered on October 26, 2014, in Los Angeles.
In the United States, it was first released on film stock, expanding to venues using digital projectors.
The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014.
It received acclaim for its performances, direction, screenplay, musical score, visual effects, ambition, themes, and emotional weight.
It has also received praise from many astronomers for its scientific accuracy and portrayal of theoretical astrophysics. Since its premiere, Interstellar gained a cult following,[5] and now is regarded by many sci-fi experts as one of the best science-fiction films of all time.
Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades"""

# 문장을 나누어 리스트로 만듭니다.
texts = text.split('.')

# 공백과 줄바꿈 문자를 삭제합니다.
texts = [t.strip(' \n') for t in texts]

### 2. 문장을 임베딩하기

In [ ]:
import numpy as np

# 임베딩을 만듭니다.
response = co.embed(
  texts=texts,
  input_type="search_document",
).embeddings

embeds = np.array(response)
print(embeds.shape)

(15, 4096)

### 3. 검색 인덱스 구축하기

In [ ]:
import faiss

dim = embeds.shape[1]
index = faiss.IndexFlatL2(dim)
index.add(np.float32(embeds))

### 4. 인덱스 검색하기

In [ ]:
import pandas as pd

def search(query, number_of_results=3):

  # 1. 쿼리의 임베딩을 만듭니다.
  query_embed = co.embed(texts=[query],
                input_type="search_query",).embeddings[0]

  # 2. 최근접 이웃을 추출합니다.
  distances, similar_item_ids = index.search(np.float32([query_embed]),
                                             number_of_results)

  # 3. 데이터프레임을 사용해 출력을 준비합니다.
  texts_np = np.array(texts) # 인덱싱을 쉽게 하기 위해 텍스트 리스트를 넘파이 배열로 변환합니다.
  results = pd.DataFrame(data={'텍스트': texts_np[similar_item_ids[0]],
                               '거리': distances[0]})

  # 4. 결과를 출력하고 반환합니다.
  print(f"쿼리:'{query}'\n최근접 이웃:")
  return results

In [ ]:
query = "how precise was the science"
results = search(query)
results

쿼리:'how precise was the science'
최근접 이웃:

                                                 텍스트            거리
0  It has also received praise from many astronom...  10757.366211
1  Caltech theoretical physicist and 2017 Nobel l...  11566.133789
2  Interstellar uses extensive practical and mini...  11922.839844

### 5. 키워드 검색 함수와 비교

In [ ]:
from rank_bm25 import BM25Okapi
from sklearn.feature_extraction import _stop_words
import string

def bm25_tokenizer(text):
    tokenized_doc = []
    for token in text.lower().split():
        token = token.strip(string.punctuation)

        if len(token) > 0 and token not in _stop_words.ENGLISH_STOP_WORDS:
            tokenized_doc.append(token)
    return tokenized_doc

In [ ]:
from tqdm import tqdm

tokenized_corpus = []
for passage in tqdm(texts):
    tokenized_corpus.append(bm25_tokenizer(passage))

bm25 = BM25Okapi(tokenized_corpus)

100%|██████████| 15/15 [00:00<00:00, 49500.05it/s]

In [ ]:
def keyword_search(query, top_k=3, num_candidates=15):
    print("입력 질문:", query)

    ##### BM25 검색 (어휘 검색) #####
    bm25_scores = bm25.get_scores(bm25_tokenizer(query))
    top_n = np.argpartition(bm25_scores, -num_candidates)[-num_candidates:]
    bm25_hits = [{'corpus_id': idx, 'score': bm25_scores[idx]} for idx in top_n]
    bm25_hits = sorted(bm25_hits, key=lambda x: x['score'], reverse=True)

    print(f"탑-3 어휘 검색 (BM25) 결과")
    for hit in bm25_hits[0:top_k]:
        print("\t{:.3f}\t{}".format(hit['score'], texts[hit['corpus_id']].replace("\n", " ")))

In [ ]:
keyword_search(query = "how precise was the science")

입력 질문: how precise was the science
탑-3 어휘 검색 (BM25) 결과
	1.789	Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan
	1.373	Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar
	0.000	It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine

### 밀집 검색의 단점

In [ ]:
query = "What is the mass of the moon?"
results = search(query)
results

쿼리:'What is the mass of the moon?'
최근접 이웃:

                                                 텍스트            거리
0  Cinematographer Hoyte van Hoytema shot it on 3...  12854.443359
1  The film had a worldwide gross over $677 milli...  13301.007812
2  It has also received praise from many astronom...  13332.000977

## 리랭킹 예제

In [ ]:
query = "how precise was the science"
results = co.rerank(query=query, documents=texts, top_n=3, return_documents=True)
results.results

[RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='It has also received praise from many astronomers for its scientific accuracy and portrayal of theoretical astrophysics'), index=12, relevance_score=0.15239799),
 RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014'), index=10, relevance_score=0.050354082),
 RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan'), index=0, relevance_score=0.0350424)]

In [ ]:
for idx, result in enumerate(results.results):
    print(idx, result.relevance_score , result.document.text)

0 0.15239799 It has also received praise from many astronomers for its scientific accuracy and portrayal of theoretical astrophysics
1 0.050354082 The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014
2 0.0350424 Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan

In [ ]:
def keyword_and_reranking_search(query, top_k=3, num_candidates=10):
    print("입력 질문:", query)

    ##### BM25 검색 (어휘 검색) #####
    bm25_scores = bm25.get_scores(bm25_tokenizer(query))
    top_n = np.argpartition(bm25_scores, -num_candidates)[-num_candidates:]
    bm25_hits = [{'corpus_id': idx, 'score': bm25_scores[idx]} for idx in top_n]
    bm25_hits = sorted(bm25_hits, key=lambda x: x['score'], reverse=True)

    print(f"탑-3 어휘 검색 (BM25) 결과")
    for hit in bm25_hits[0:top_k]:
        print("\t{:.3f}\t{}".format(hit['score'], texts[hit['corpus_id']].replace("\n", " ")))

    # 리랭킹 추가
    docs = [texts[hit['corpus_id']] for hit in bm25_hits]

    print(f"\n리랭킹으로 얻은 탑-3 결과 ({len(bm25_hits)}개의 BM25 결과를 재조정함)")
    results = co.rerank(query=query, documents=docs, top_n=top_k, return_documents=True)
    for hit in results.results:
        print("\t{:.3f}\t{}".format(hit.relevance_score, hit.document.text.replace("\n", " ")))

In [ ]:
keyword_and_reranking_search(query = "how precise was the science")

입력 질문: how precise was the science
탑-3 어휘 검색 (BM25) 결과
	1.789	Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan
	1.373	Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar
	0.000	Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles

리랭킹으로 얻은 탑-3 결과 (10개의 BM25 결과를 재조정함)
	0.152	It has also received praise from many astronomers for its scientific accuracy and portrayal of theoretical astrophysics
	0.050	The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014
	0.035	Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan

## RAG

### 예: LLM API를 사용한 근거 기반 생성

In [ ]:
query = "income generated"

# 1- 검색
# 여기서는 임베딩 검색을 사용하지만 하이브리드 방식이 이상적입니다.
results = search(query)

# 2- 근거 기반 생성
docs_dict = [{'text': text} for text in results['텍스트']]
response = co.chat(
    message = query,
    documents=docs_dict
)

print(response.text)

쿼리:'income generated'
최근접 이웃:
The film Interstellar generated over $677 million worldwide, or $773 million including subsequent re-releases.

In [ ]:
response

NonStreamedChatResponse(text='The film Interstellar generated over $677 million worldwide, or $773 million including subsequent re-releases.', generation_id='d721e9d6-8c75-4e9d-90aa-7884e4ed4d30', response_id='f8390bc7-f84e-43c1-83b3-557c64f0e737', citations=[ChatCitation(start=9, end=21, text='Interstellar', document_ids=['doc_2'], type='TEXT_CONTENT'), ChatCitation(start=32, end=59, text='over $677 million worldwide', document_ids=['doc_0'], type='TEXT_CONTENT'), ChatCitation(start=64, end=110, text='$773 million including subsequent re-releases.', document_ids=['doc_0'], type='TEXT_CONTENT')], documents=[{'id': 'doc_2', 'text': 'Interstellar uses extensive practical and miniature effects and the company Double Negative created additional digital effects'}, {'id': 'doc_0', 'text': 'The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014'}], is_search_required=None, search_queries=None, search_results=None, finish_reason='COMPLETE', tool_calls=None, chat_history=[UserMessage(role='USER', message='income generated', tool_calls=None), ChatbotMessage(role='CHATBOT', message='The film Interstellar generated over $677 million worldwide, or $773 million including subsequent re-releases.', tool_calls=None)], meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(images=None, input_tokens=106.0, image_tokens=None, output_tokens=25.0, search_units=None, classifications=None), tokens=ApiMetaTokens(input_tokens=1763.0, output_tokens=58.0), cached_tokens=0.0, warnings=None))

In [ ]:
response.citations

[ChatCitation(start=9, end=21, text='Interstellar', document_ids=['doc_2'], type='TEXT_CONTENT'),
 ChatCitation(start=32, end=59, text='over $677 million worldwide', document_ids=['doc_0'], type='TEXT_CONTENT'),
 ChatCitation(start=64, end=110, text='$773 million including subsequent re-releases.', document_ids=['doc_0'], type='TEXT_CONTENT')]

### 예: 로컬 모델을 사용한 RAG

#### 생성 모델 로드하기

In [ ]:
!wget https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf

--2026-04-02 02:28:07--  https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf
Resolving huggingface.co (huggingface.co)... 3.165.160.12, 3.165.160.61, 3.165.160.11, ...
Connecting to huggingface.co (huggingface.co)|3.165.160.12|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cas-bridge.xethub.hf.co/xet-bridge-us/662698108f7573e6a6478546/df220524a4e4a750fe1c325e41f09ff69137f38b52d8831ba22dcbee3cc8ab6d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20260402%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260402T022807Z&X-Amz-Expires=3600&X-Amz-Signature=b4f6cd0f914df59e5bab744d4fe40619d5dee87f99e56e758a00fef0edecc2d3&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Phi-3-mini-4k-instruct-q4.gguf%3B+filename%3D%22Phi-3-mini-4k-instruct-q4.gguf%22%3B&x-amz-checksum-mode=ENABLED&x-id=GetObject&Expires=1775100487&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc3NTEwMDQ4N319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82NjI2OTgxMDhmNzU3M2U2YTY0Nzg1NDYvZGYyMjA1MjRhNGU0YTc1MGZlMWMzMjVlNDFmMDlmZjY5MTM3ZjM4YjUyZDg4MzFiYTIyZGNiZWUzY2M4YWI2ZCoifV19&Signature=AnV2l3TEsCpxjA9-K8GwIxiuTydAetRxQ4XfzHqAyzeo3Nq-pwD64a4MQBHWHcZc4lLWKiwMHlpjyVZbDpMYNguaqPX5r72rLBayZv-8DQtQJUgbn3xw%7EQZUfFbumSehKtOaYXmwZKaq%7E7IQcZU2meLMDDRvOZXKUcubtHUFuYRxeYiaj2jBLNk3wLqlPg7RAHE1GhILC4I3DMWWouOh7aJpjHloyw0gbCzEdCAUWs2xCLicV84UyDEQjbVNjDVJnRDqhZ8hMmwTuIaVUHamOkbwZkneSGxurI8baAIfkqQcNf6GCCEUBl-c21-l3L4xi43skwDNbawHRLBkBTnVjQ__&Key-Pair-Id=K2L8F4GPSG1IFC [following]
--2026-04-02 02:28:07--  https://cas-bridge.xethub.hf.co/xet-bridge-us/662698108f7573e6a6478546/df220524a4e4a750fe1c325e41f09ff69137f38b52d8831ba22dcbee3cc8ab6d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20260402%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260402T022807Z&X-Amz-Expires=3600&X-Amz-Signature=b4f6cd0f914df59e5bab744d4fe40619d5dee87f99e56e758a00fef0edecc2d3&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Phi-3-mini-4k-instruct-q4.gguf%3B+filename%3D%22Phi-3-mini-4k-instruct-q4.gguf%22%3B&x-amz-checksum-mode=ENABLED&x-id=GetObject&Expires=1775100487&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc3NTEwMDQ4N319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82NjI2OTgxMDhmNzU3M2U2YTY0Nzg1NDYvZGYyMjA1MjRhNGU0YTc1MGZlMWMzMjVlNDFmMDlmZjY5MTM3ZjM4YjUyZDg4MzFiYTIyZGNiZWUzY2M4YWI2ZCoifV19&Signature=AnV2l3TEsCpxjA9-K8GwIxiuTydAetRxQ4XfzHqAyzeo3Nq-pwD64a4MQBHWHcZc4lLWKiwMHlpjyVZbDpMYNguaqPX5r72rLBayZv-8DQtQJUgbn3xw%7EQZUfFbumSehKtOaYXmwZKaq%7E7IQcZU2meLMDDRvOZXKUcubtHUFuYRxeYiaj2jBLNk3wLqlPg7RAHE1GhILC4I3DMWWouOh7aJpjHloyw0gbCzEdCAUWs2xCLicV84UyDEQjbVNjDVJnRDqhZ8hMmwTuIaVUHamOkbwZkneSGxurI8baAIfkqQcNf6GCCEUBl-c21-l3L4xi43skwDNbawHRLBkBTnVjQ__&Key-Pair-Id=K2L8F4GPSG1IFC
Resolving cas-bridge.xethub.hf.co (cas-bridge.xethub.hf.co)... 18.238.238.109, 18.238.238.105, 18.238.238.29, ...
Connecting to cas-bridge.xethub.hf.co (cas-bridge.xethub.hf.co)|18.238.238.109|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2393231072 (2.2G)
Saving to: ‘Phi-3-mini-4k-instruct-q4.gguf’

Phi-3-mini-4k-instr 100%[===================>]   2.23G   214MB/s    in 19s

2026-04-02 02:28:26 (121 MB/s) - ‘Phi-3-mini-4k-instruct-q4.gguf’ saved [2393231072/2393231072]

In [ ]:
from langchain_community.llms import LlamaCpp

# 여러분의 컴퓨터에 다운로드한 모델의 경로를 입력하세요!
llm = LlamaCpp(
    model_path="Phi-3-mini-4k-instruct-q4.gguf",
    n_gpu_layers=-1,
    max_tokens=500,
    n_ctx=4096,
    seed=42,
    verbose=False
)

llama_context: n_batch is less than GGML_KQ_MASK_PAD - increasing to 64

#### 임베딩 모델 로드하기

In [ ]:
from langchain_huggingface import HuggingFaceEmbeddings

# 텍스트를 수치 표현으로 변환하기 위한 임베딩 모델
embedding_model = HuggingFaceEmbeddings(
    model_name='BAAI/bge-small-en-v1.5'
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

#### 벡터 데이터베이스 구축

In [ ]:
from langchain_community.vectorstores import FAISS

# 로컬 벡터 데이터베이스를 만듭니다.
db = FAISS.from_texts(texts, embedding_model)

#### RAG 프롬프트

In [ ]:
from langchain_core.prompts import PromptTemplate
from langchain_classic.chains import RetrievalQA


# 프롬프트 템플릿을 만듭니다.
template = """<|user|>
Relevant information:
{context}

Provide a concise answer the following question using the relevant information provided above:
{question}<|end|>
<|assistant|>"""
prompt = PromptTemplate(
    template=template,
    input_variables=["context", "question"] # 여기에 검색 결과와 질문이 들어갑니다.
)

# RAG 파이프라인
rag = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type='stuff',
    retriever=db.as_retriever(),
    chain_type_kwargs={
        "prompt": prompt
    },
    verbose=True
)

In [ ]:
rag.invoke('Income generated')

> Entering new RetrievalQA chain...

> Finished chain.

{'query': 'Income generated',
 'result': ' The information provided does not directly relate to the income generated from "Interstellar." However, it mentions that Kip Thorne\'s involvement and the use of special effects by Double Negative could have contributed to the film\'s success. Income generation would depend on various factors like box office earnings, DVD/Blu-ray sales, and additional revenue from tie-in books or consultations, none of which are specified in the given information.'}